# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from course_project/Trilateration.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import course_project.msg

class Trilateration(genpy.Message):
  _md5sum = "45e1ed04607c6f7e36ae2697ced8826f"
  _type = "course_project/Trilateration"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """Landmark landmarkA
Landmark landmarkB
Landmark landmarkC

================================================================================
MSG: course_project/Landmark
float32 x
float32 y
float32 distance
float32 variance
"""
  __slots__ = ['landmarkA','landmarkB','landmarkC']
  _slot_types = ['course_project/Landmark','course_project/Landmark','course_project/Landmark']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       landmarkA,landmarkB,landmarkC

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Trilateration, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.landmarkA is None:
        self.landmarkA = course_project.msg.Landmark()
      if self.landmarkB is None:
        self.landmarkB = course_project.msg.Landmark()
      if self.landmarkC is None:
        self.landmarkC = course_project.msg.Landmark()
    else:
      self.landmarkA = course_project.msg.Landmark()
      self.landmarkB = course_project.msg.Landmark()
      self.landmarkC = course_project.msg.Landmark()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_12f().pack(_x.landmarkA.x, _x.landmarkA.y, _x.landmarkA.distance, _x.landmarkA.variance, _x.landmarkB.x, _x.landmarkB.y, _x.landmarkB.distance, _x.landmarkB.variance, _x.landmarkC.x, _x.landmarkC.y, _x.landmarkC.distance, _x.landmarkC.variance))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.landmarkA is None:
        self.landmarkA = course_project.msg.Landmark()
      if self.landmarkB is None:
        self.landmarkB = course_project.msg.Landmark()
      if self.landmarkC is None:
        self.landmarkC = course_project.msg.Landmark()
      end = 0
      _x = self
      start = end
      end += 48
      (_x.landmarkA.x, _x.landmarkA.y, _x.landmarkA.distance, _x.landmarkA.variance, _x.landmarkB.x, _x.landmarkB.y, _x.landmarkB.distance, _x.landmarkB.variance, _x.landmarkC.x, _x.landmarkC.y, _x.landmarkC.distance, _x.landmarkC.variance,) = _get_struct_12f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_12f().pack(_x.landmarkA.x, _x.landmarkA.y, _x.landmarkA.distance, _x.landmarkA.variance, _x.landmarkB.x, _x.landmarkB.y, _x.landmarkB.distance, _x.landmarkB.variance, _x.landmarkC.x, _x.landmarkC.y, _x.landmarkC.distance, _x.landmarkC.variance))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.landmarkA is None:
        self.landmarkA = course_project.msg.Landmark()
      if self.landmarkB is None:
        self.landmarkB = course_project.msg.Landmark()
      if self.landmarkC is None:
        self.landmarkC = course_project.msg.Landmark()
      end = 0
      _x = self
      start = end
      end += 48
      (_x.landmarkA.x, _x.landmarkA.y, _x.landmarkA.distance, _x.landmarkA.variance, _x.landmarkB.x, _x.landmarkB.y, _x.landmarkB.distance, _x.landmarkB.variance, _x.landmarkC.x, _x.landmarkC.y, _x.landmarkC.distance, _x.landmarkC.variance,) = _get_struct_12f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_12f = None
def _get_struct_12f():
    global _struct_12f
    if _struct_12f is None:
        _struct_12f = struct.Struct("<12f")
    return _struct_12f
